### ISSUE TITLE
Add support for if%hw and match%hw outside of [%hw ...]

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_hardcaml#18]
The `if%hw` construct is only valid within a `[%hw]` scope.

**Comment by andrewray** [comment]
I guess the other way to look at it is `if%hw` is valid at any scope since it is already differentiated.

**Comment by xguerin** [comment]
That was my original assessment but in the current state of affairs a `if%hw` outside of a `[%hw]` scope does not generate a `mux2` command.

**Comment by andrewray** [comment]
I **_think_** `if%hw ...` and `[%hw if ... ]` can be matched separately in the mapper.  The later recurses into a different mapper.  Both mappers, in this case, could potentially recognise the `if%hw` form.

I am not totally sure this logic is correct...

**Comment by xguerin** [comment]
Unfortunately the AST for`if%hw ...` and `[%hw if ...]` are isomorphic. The solution I am implementing simply adds support for `if%hw` as top-level elements. I am also adding support for `match%hw` as a top-level element as well as the `%hw.signed` form at the top-level.

**Comment by andrewray** [comment]
> Unfortunately the AST forif%hw ... and [%hw if ...] are isomorphic

I don't think so actually.  In a `mapper`, I think you can pick out the `keyword%ext` syntax specifically.  I will have to double check that assertion though.

**Comment by xguerin** [comment]
I checked with the `dumpast` tool. There may be some specificities of the `mapper` API I am not aware though :/

**Comment by xguerin** [comment]
I pushed a working version in the `toplevel_if_match` branch. It's a bit more involved because of the availability of both `%hw` and `%hw.signed` extensions. In the proposed version, the `%hw` and `%hw.signed` used on `if` and `match` actually alter the signedness of the content.

For instance, the following:

```ocaml
let some_fn a b c d =
  if%hw a then a > b else
  if%hw.signed c then d else
  a > b
```

gives:

```ocaml
let some_fn a b c d =
  resize_op2 ~resize:uresize (mux2 a) (resize_op2 ~resize:uresize (>:) a b)
    (resize_op2 ~resize:sresize (mux2 c) d
       (resize_op2 ~resize:sresize (>+) a b))
```

Further:

```ocaml
let some_fn a b c d =
  if%hw a then a > b else
  if%hw.signed c then d else
  [%hw a > b]
```

gives:

```ocaml
let some_fn a b c d =
  resize_op2 ~resize:uresize (mux2 a) (resize_op2 ~resize:uresize (>:) a b)
    (resize_op2 ~resize:sresize (mux2 c) d
       (resize_op2 ~resize:uresize (>:) a b))
```

I am not quite sure that the sign swapping here makes a lot of sense. It would be fairly trivial to add a restriction to keep the user from doing it.

**Comment by xguerin** [comment]
I pushed another version in branch `top_level_if_no_sign_swap` that forbids sign swapping in the middle of a [%hw ] block.

**Comment by xguerin** [comment]
I'm going to merge the `top_level_if_no_sign_swap` branch for now as I need to pin that repo across multiple machines. We can always iterate over it later if needed.
