### ISSUE TITLE
Improve error reporting of malformed`if%hw`

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_hardcaml#19]
The following:

```ocaml
let%hw upd_curseq rsa rsb v =
  if%hw rsa.rs_vld land (lnot rsb.rs_vld) then
    0h
  else if%hw rsa.rs_vld land (lnot rsb.rs_vld) then
    1h
```

Throws:

```
Error: Uninterpreted extension 'hw'.
```

On the line with he second `if%hw` statement.

**Comment by andrewray** [comment]
For some reason, I missed this issue - 

```
let%hw foo = if%hw 1h then 2h else if%hw 0h then 7h else 0h;;
```

is ok, but

```
let%hw foo = if%hw 1h then 2h else if%hw 0h then 7h;;
```

is not.  That is to be expected - the 2nd `if` does not have an `else` which is required for the underlying mux2.  The error reported could be more expressive though...

**Comment by xguerin** [comment]
Aha, yes, good catch. I'll look into that.
