### ISSUE TITLE
Add support for let%hw as stritem

### ISSUE THREAD

**Issue by andrewray** [xguerin/ppx_hardcaml#2]
It would be useful to be able to write

```
let%hw x = ...
``` 

as top level expressions, which I think means adding some mapper clauses to rewrite appropriate stritem bindings.

**Comment by xguerin** [comment]
I am thinking to apply `[%hw]` recursively to all expressions contained in that `let%hw` structure. Is that what you also have in mind ? Or are you thinking about something less thorough ?

**Comment by andrewray** [comment]
I think there are 2 separate issues here (but I might be wrong as my ppx foo is only so so).

```
let x = 
  let%hw x = <expr> in
  ...
```

in this context, the rewrite should be (fully) recursive within `<expr>` and would look equivalent to

```
let x = 
  let x = [%hw <expr>] in
  ...
```

In the following case I believe the `let%hw` won't be picked up by the expression mapper, as it is a stritem (ie a top-level let without an `in` part).  However, the logic applied to `<expr>` is exactly the same.

```
let%hw x = <expr>;;
```

or equivalently

```
let x = [%hw <expr>];;
```

**Comment by andrewray** [comment]
FWIW - the `let%hw` as a stritem thing is mostly useful when fiddling around in utop and not hugely important - it's something I can patch in at a later date if you like.

**Comment by xguerin** [comment]
> In the following case I believe the let%hw won't be picked up by the expression mapper, as it is a stritem (ie a top-level let without an in part). However, the logic applied to <expr> is exactly the same.

True. However, the current policy for mapping the `let%hw` expression is to remap the left-hand side of the `in` and not the right-hand side. For example:

```ocaml
let%hw v = expr1 in expr2;;
```
is mapped to:
```ocaml
let v = [%hw expr1] in expr2;;
```

For the structural `let%hw` construct, we could either follow that policy, or also remap the right-hand side expression. For example:

```ocaml
let%hw v =
  let w = expr1 in expr2;;
```

would be mapped to:

```ocaml
let v =
 let w = [%hw expr1] in [% expr2];;
```

My thinking is that the expectation of the scope of a structural `let` construct is inclusive, i.e. all expressions after the `=` should be considered as part of the `[%hw]` scope.

**Comment by andrewray** [comment]
Agreed but with the slight clarification that I would view

```
let%hw v =
  let w = expr1 in expr2;;
```

as

```
let v =
 [%hw let w = expr1 in expr2];;
```

That is `(let .. = .. in ..)` is an expression itself.  This would also extend to cases like

```
let ... = 
  let%hw x = ... 
   let y = ... in
   y
  in
  ...
```

where y would be rewritten as it is an expression within x.

Anyway, I am pretty sure we are talking about the same thing!

**Comment by xguerin** [comment]
> where y would be rewritten as it is an expression within x

I see your point. However, I fear that rewriting all expressions in the scope of a `let%hw` rewritten variable may be too inclusive. Following that scheme, it would be easy to lose track of context in large functions, especially in the future if we also add support for rewriting `match` and `if` expressions.

> Anyway, I am pretty sure we are talking about the same thing!

Most likely :) Let me write the fully recursive version for the structural `let`. We can resume the discussion on expression `let` from that point on.

**Comment by xguerin** [comment]
The solution I came up with implements two extensions:

* `%hw` which does only recurse on the expression of a let value binding
* `%hw'` which does recurse on each expression

The structural `let` binding only supports `[%hw]` as extension but actually defaults to `[%hw']`. This solution leads to the following combinations (cf. unit test file):

##### A. Structural let, full recursion

```ocaml
let%hw combine_signals a b =
  let sub_a = a.[11,08]
  and sub_b = b.[15,12]
  in
  sub_a @ sub_b

let structural_let context =
  let s0 = const "16'h0F00" in
  let s1 = const "16'hF000" in
  assert_equal (combine_signals s0 s1) (const "8'hFF")
```

##### B. Expression let, full recursion

```ocaml
let ext_rec_let context =
  let s0.       = const "16'h0F00" in
  let s1        = const "16'hF000" in
  let%hw' sub_0 = s0.[11,08] in
  let sub_1     = s1.[15,12] in
  let res       = sub_0 @ sub_1 in
  assert_equal res (const "8'hFF")
```

##### C. Expression let, left-hand recursion

```ocaml
let ext_rec_let context =
  let s0       = const "16'h0F00" in
  let s1       = const "16'hF000" in
  let%hw sub_0 = s0.[11,08] in
  let%hw sub_1 = s1.[15,12] in
  let%hw res   = sub_0 @ sub_1 in
  assert_equal res (const "8'hFF")
```

**Comment by andrewray** [comment]
Hmmm, I am going to have to have a think about this.  I don't understand the "B" case at all - if you thought I was advocating that the rewrite should extend beyond the in (as this appears to do) then sorry for the misunderstanding but I don't see that as sensible.

Also, playing with the latest code I can do

```
let foo = 
  let%hw x = 
    let x = a + b in
    let y = a - b in
    x,y
  in 
  x;;
```

which I /was/ advocating for, but didn't think you agreed with.

**Comment by xguerin** [comment]
> Hmmm, I am going to have to have a think about this. I don't understand the "B" case at all - if you thought I was advocating that the rewrite should extend beyond the in (as this appears to do) then sorry for the misunderstanding but I don't see that as sensible

This is indeed what I thought you were advocating for :p I don't think that is sensible either :)

The B case can stay internal and not be advertised. It is still necessary for the A case and the case you mention. I can go back to using hw*, invalid syntax as far as the lexer is concerned but accepted by AST parser.  

> which I /was/ advocating for, but didn't think you agreed with

That hit me last night. If the rewriting applies to the expression of the value binding, it must apply recursively.

**Comment by xguerin** [comment]
I came up with another method to achieve the same result without using another extension. The rewriter now simply carries around a `recurse` expression attribute that is used to decide whether or not the rewriter needs to recurse on all sub-expressions. As a result, the "B" is not available anymore.

**Comment by andrewray** [comment]
I am still not exactly sure whether we mean the same thing when we say recursion or not, and especially what it means when you turn it off.

I'm having a good look through the code to see what it is doing.

**Comment by xguerin** [comment]
> I'm having a good look through the code to see what it is doing.

Ok. Hopefully that will clarify things :)

**Comment by xguerin** [comment]
> I'm having a good look through the code to see what it is doing.

Ok. Hopefully that will clarify things :)

EDIT - here are the rules that the rewriter basically follows:

1. In case of an expression that is not a `let`, rewrite if necessary (bin ops, String.get, etc..)
2. In case of an expression that is a `let`, value-bind expressions are recursively rewritten
3. In case of a structure item that is a `let`, all expressions are recursively rewritten

By *recursively* rewritten I mean that all sub-expression within an expression will be rewritten. In case of a `let`, that means all value-bind expressions **as well as** the expression after the `in` keyword.

As a result, when a value-bind expression is a `let` expression, as for `x` below:

```ocaml
let foo = 
  let%hw x = 
    let x = a + b in
    let y = a - b in
    x,y
  in 
  x;;
```
then all sub-expressions of that expression will be rewritten, i.e. `a + b` and `a - b` **and** `x, y`.

**Comment by andrewray** [comment]
That's very helpful, thanks.

**Comment by andrewray** [comment]
https://gist.github.com/andrewray/2c8b2cda626fcd3bed8ef03c8ed3c5bb

This is my take.  To be discussed...

**Comment by xguerin** [comment]
Playing around with your gist, I saw the following behavior:

```ocaml
let some a b =
  let%hw c = a + 1 in
  b + c
```
producing:

```ocaml
let some a b =
  let c = a +: 1 in
  b +: c
```

where both the value-bind expression and the core expression are rewritten. Is that the expected output ? I thought from a previous comment that you (as I) did not find that to be sensible.

**Comment by andrewray** [comment]
Your right it shouldn't be like that.  I had a quick look at some ppx documentation and apparently

```
let%hw p = e0 in e1
```

is a shortcut for

```
[%hw let p = e0 in e1]
```

Its fixable by changing the expr mapper as follows

```
    expr = (fun mapper expr ->
      match expr with

      (* 'let%hw pat = <expr> in ...' *)
      | [%expr [%hw let [%p? var] = [%e? e0] in [%e? e1]]] ->
        [%expr let [%p default_mapper.pat mapper var] = 
          [%e hwexpr {mapper with expr=hwexpr} e0] in
          [%e default_mapper.expr mapper e1]]

      (* [%hw expr] *)
      | [%expr [%hw [%e? e]]] ->
        [%expr [%e hwexpr {mapper with expr=hwexpr} e]]

      | _ -> default_mapper.expr mapper expr);
```

**Comment by xguerin** [comment]
So now we are encountering the same conundrum as I had previously :) This works well except when:

1. we are rewriting a `let` structure item
2. the value-bind is itself made of `let` expressions

In both of these cases, the expectation is that **all** expressions (not just value bindings) are rewritten. To address that problem, I carry down a `hwrec` attribute that specify that such a behavior must be implemented.

**Comment by andrewray** [comment]
For 1. it works the way I would expect:

```
let%hw some a b = 
  let c = a+1h in  (* everything rewritten *)
  b+c;;
```

Similarly for 2.

```
et some a b = 
  let%hw c = 
    let d = a+1h in d (* rewritten as expected - its the expression inside %hw *)
  in
  b +: c;;  (* not rewritten - must use +: *)
```

This is the behaviour I expect, do you think this is wrong, or have a broken example?

**Comment by xguerin** [comment]
My bad, You are perfectly right. It works as expected.

**Comment by xguerin** [comment]
Actually, there is a snag with multiple value binds:

```ocaml
let some a b =
  let%hw c = a + 1 and d = b + 1 in
  c + d
```

```ocaml
let some a b =
  let c = a +: 1 and d = b +: 1  in
  c +: d
```

The initial `let` expression is not matched and it defaults to the next, more general one. I don't think it's possible to extract list of value binds using `metaquot`, so I can just bring in the solution I currently have for that.

**Comment by andrewray** [comment]
There's another bug as well

```
let x = 
  let%hw a = 3h in 
  let%hw b = 2h in (* fails here *) 
  a +: b;;
```

This is the fix

```
     (* 'let%hw pat = <expr> in ...' *)
      | [%expr [%hw let [%p? var] = [%e? e0] in [%e? e1]]] ->
        [%expr let [%p default_mapper.pat mapper var] = 
          [%e hwexpr {mapper with expr=hwexpr} e0] in
          [%e (*here*) mapper.expr mapper e1]] 
```

**Comment by andrewray** [comment]
Hmmm, I note other issues like `let rec ...`.  Are we fighting the system here?

I thought `let%hw p = e0 in e1` made sense only as `let p = [%hw e0] in e1` but ocaml has different rules.  Maybe we would be better just doing what the system expects?

**Comment by andrewray** [comment]
Ok, so lwt.ppx seems to do something similar to what we want https://github.com/ocsigen/lwt/blob/master/src/ppx/ppx_lwt_ex.ml

I think it deals with `let%hw`, `let%hw ... and ... and` and disallows `let%hw rec`.

**Comment by xguerin** [comment]
See #11, closing.
