### ISSUE TITLE
Migrate to OMP and jbuilder

### ISSUE THREAD

**Issue by xguerin** [xguerin/ppx_hardcaml#22]
* OMP to make the rewriter future proof
* jbuilder because it's just a whole lot easier

**Comment by andrewray** [comment]
FYI - I have been using `ppx_deriving_hardcaml` with jbuilder using a temporary bodge from @diml

https://github.com/diml/ppx_deriving_omp

Hopefully soon `ppx_deriving` will get the required updates.

**Comment by xguerin** [comment]
Nice, I was not aware of that bodge 👍 Were there any change required to the `ppx_deriving_hardcaml` code ?

**Comment by andrewray** [comment]
I added a linkall flag, which may or may not have been needed (though it definitely will when ppx_deriving gets fixed, apparently).

https://github.com/ujamjar/ppx_deriving_hardcaml/commit/7759d4371daa6904bda6d8bea5242aea57628d38
