### ISSUE TITLE
mixing constants into expressions

### ISSUE THREAD

**Issue by andrewray** [xguerin/ppx_hardcaml#6]
```
let x = [%hw (1 + a) land 3]
```

Each operator would need to consider 4 variants with mixtures of integer constants and expressions (assumed to be bits or signals) then rewrite them appropriately.  The various `+:.` style hardcaml operators are an example of this, but rewriting through ppx would be much more powerful.

**Comment by xguerin** [comment]
Yes, I was pondering how to supports these operators. With immediate values, the support is trivial. However, any expression returning an `int` is likely out of scope.

**Comment by andrewray** [comment]
Agreed.  Arbitrary ints would still need to use the `consti x n` syntax, but being able to mix in the odd integer constant into expressions is very useful.

Note also that the hardcaml operators with constants only accept them on the right hand argument.  This is ok for most of them (swapping args where needed) except for `-:.` which would need something different.

**Comment by andrewray** [comment]
Thinking some more about this, if built on top the signed/unsigned enhancement, you could just detect integer constants and turn them directly into a "big enough" hardware constant.

**Comment by xguerin** [comment]
> ...and turn them directly into a "big enough" hardware constant.

Yes. I was thinking about that possibility, which would solve the `-:.` operator problem. The generated code would be a bit verbose though, as I would have to resort to a lambda to get the width of the signal:

```ocaml
let%hw = 0 - some_sig in ...
```

would become:

```ocaml
let%hw = ((fun some_sig -> (consti (width some_sig) 0) -: some_sig) some_sig) in ...
```

However, that most likely does not matter anyway.

**Comment by andrewray** [comment]
I was actually thinking something more like;

```
let%hw x = 6
```

which would get turned into 

```
let x = consti 3 6
```

The width would get inferred from the constant itself.  This would add 1 more rewrite rule.  For resizing of operators you could have;

```
let%hw c = a + b
```

which could be turned into

```
let c = (uresize a (max (width a) (width b))) +:  (uresize a (max (width a) (width b)))
```

Alternatively, you could also use the Unsigned/Signed modules ie

```
let c = Unsigned.(to_signal ((of_signal a) +: (of_signal b)))
```

(the semantics are a bit different here in that `c`s width is set to `1 + max (width a) (width b)` to avoid overflow)

**Comment by xguerin** [comment]
Oh I see. But in the mixed case:

```ocaml
let%hw b = a + 2
```

if we convert immediates into signals as a generic solution to handle binary operators, the length of the converted signal needs to be taken from the length of the signal member.

**Comment by andrewray** [comment]
The resizing rules should sort this out "for free".  

```
let%hw a = 6 (* 3 bit signal *)
let%hw b = a + 1 (* 3 bit + 1 bit *)
```

For b the 1 will be converted to a 1 bit signal.  The addition (as will all operators) will then receive 2 signals of potentially different widths.  Therefore, we check the widths and resize them both to `max (width left_arg) (width right_arg)` (acutally, only one needs resizing, but that's just a detail).  We can do this because we are assuming that all signals are unsigned so we can just zero extend them to an appropriate size.  This is true of comparison, bitwise, + and - operators (multiplication and concat will just work).

One big downside I just realised is that some sub-expression which needs an actual int would be a problem.

```
let%hw x = a + consti 2 1
```

Perhaps this isn't such a good idea...and it should only be rewritten in context of an operator argument as you are suggesting.

**Comment by xguerin** [comment]
I can add a special case to `let%hw` to convert immediates. But that may confuse things.

**Comment by andrewray** [comment]
I realised earlier that I had totally forgotten about the new constant format specifiers, which makes this notion of generic constants possible ie

```
let%hw x = 1h
let%hw y = 0xdh
let%hw z = 0b1010h
let%hw pow2 n x = x @ zero n
let%hw sum = x + y + (pow2 3 (2h + z))
```

**Comment by xguerin** [comment]
Indeed. I'll look into it.
